FROM node:latest as build

FROM gcr.io/distroless/base-debian13:nonroot

COPY --from=build /lib/x86_64-linux-gnu/libatomic.so.1  /lib/x86_64-linux-gnu/libatomic.so.1 
COPY --from=build /lib/x86_64-linux-gnu/libdl.so.2   /lib/x86_64-linux-gnu/libdl.so.2
COPY --from=build /lib/x86_64-linux-gnu/libm.so.6  /lib/x86_64-linux-gnu/libm.so.6
COPY --from=build /lib/x86_64-linux-gnu/libstdc++.so.6  /lib/x86_64-linux-gnu/libstdc++.so.6
COPY --from=build /lib/x86_64-linux-gnu/libgcc_s.so.1  /lib/x86_64-linux-gnu/libgcc_s.so.1
COPY --from=build /lib/x86_64-linux-gnu/libpthread.so.0  /lib/x86_64-linux-gnu/libpthread.so.0
COPY --from=build /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6
COPY --from=build /lib64/ld-linux-x86-64.so.2  /lib64/ld-linux-x86-64.so.2        

COPY --from=build /usr/local/bin/node /usr/local/bin/node

COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /etc/group /etc/group        

USER node

CMD ["node"]